version: '3'

services:
  wordpress:
    image: wordpress:latest
    ports:
      - "80:80"
      - "443:443"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ecyadm01
      WORDPRESS_DB_PASSWORD: Secinfo07
      WORDPRESS_DB_NAME: ecytools_db
    volumes:
      - ./wpweb_files:/var/www/html
      - ./ssl:/ssl_config

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: ecytools_db
      MYSQL_USER: ecyadm01
      MYSQL_PASSWORD: Secinfo07
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db_data:/var/lib/mysql

volumes:
  wordpress_data:
  db_data:
